wandb:
  _target_: pytorch_lightning.loggers.wandb.WandbLogger
  project: ${project-name}
  name: ${name}
  save_dir: "."
  offline: False # set True to store all logs only locally
  id: null # pass correct id to resume experiment!
  log_model: False
  prefix: ""
  job_type: "train"
  group: ""
  tags: []